name       : fop
version    : '2.5'
release    : 3
source     :
    - https://archive.apache.org/dist/xmlgraphics/fop/source/fop-2.5-src.tar.gz : 783077318139d581d5f485566d1b08bfc576003c53cfbf5beaeba503a24b4005
license    : Apache-2.0
homepage   : https://xmlgraphics.apache.org/fop/
component  : programming.java
summary    : XSL-FO implementation in Java
description: |
    FOP (Formatting Objects Processor) is a print formatter driven by XSL formatting objects (XSL-FO) and an output independent formatter.

    Output formats currently supported include PDF, PS and PNG.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-11
build      : |
    export JAVA_HOME=/usr/lib64/openjdk-11
    mkdir -p fop-events/target/test-classes
    mvn -DdistributionTargetDir=$installdir/usr/share/java -Dmaven.repo.local=../local-repo -DskipTests clean install -T%YJOBS%
install    : |
    install -Dm00644 fop/lib/xmlgraphics-commons*.jar $installdir/usr/share/java/xmlgraphics-commons.jar
    install -Dm00644 fop/lib/commons-io*.jar $installdir/usr/share/java/commons-io.jar
    install -Dm00644 fop/lib/commons-logging*.jar $installdir/usr/share/java/commons-logging.jar
    install -Dm00644 fop/lib/batik-all*.jar $installdir/usr/share/java/batik-all.jar
    install -Dm00644 fop/lib/xml-apis-ext*.jar $installdir/usr/share/java/xml-apis-ext.jar
    install -Dm00644 fop/target/fop-$version.jar $installdir/usr/share/java/fop/fop.jar
    install -Dm00644 $pkgfiles/fop.conf $installdir/etc/fop.conf
    install -Dm00755 fop/fop $installdir/usr/bin/fop
